[build]
  command = "npm run build:shared && npm run build:web"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "20"

[context.production.environment]
  VITE_API_BASE = "https://api.liss11.org"

[context.deploy-preview.environment]
  VITE_API_BASE = "https://liss11-api-staging.onrender.com"

[context.branch-deploy.environment]
  VITE_API_BASE = "https://liss11-api-staging.onrender.com"

[context.staging.environment]
  VITE_API_BASE = "https://liss11-api-staging.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
