/** Inversify binding identifiers. Symbols avoid string-key collisions. */
export const TYPES = {
  PrismaClient: Symbol.for("PrismaClient"),
  MemberRepository: Symbol.for("MemberRepository"),
  VerificationTokenRepository: Symbol.for("VerificationTokenRepository"),
  PasswordResetTokenRepository: Symbol.for("PasswordResetTokenRepository"),
  ContactMessageRepository: Symbol.for("ContactMessageRepository"),
  OfficerRepository: Symbol.for("OfficerRepository"),
  BotMemberRepository: Symbol.for("BotMemberRepository"),
  RegionRepository: Symbol.for("RegionRepository"),
  AnnouncementRepository: Symbol.for("AnnouncementRepository"),
  AlbumRepository: Symbol.for("AlbumRepository"),
  EventRepository: Symbol.for("EventRepository"),
  FinancialStatementRepository: Symbol.for("FinancialStatementRepository"),
  BlogPostRepository: Symbol.for("BlogPostRepository"),
  SiteSettingRepository: Symbol.for("SiteSettingRepository"),
  AuthService: Symbol.for("AuthService"),
  ContactService: Symbol.for("ContactService"),
  EmailService: Symbol.for("EmailService"),
  StorageService: Symbol.for("StorageService"),
  PaymentRepository: Symbol.for("PaymentRepository"),
  PaystackService: Symbol.for("PaystackService"),
  PaymentService: Symbol.for("PaymentService"),
  ElectionRepository: Symbol.for("ElectionRepository"),
  ElectionService: Symbol.for("ElectionService"),
} as const;
